### ISSUE TITLE
The resource in Gitee have problem to be seen, how to fix it?

### ISSUE THREAD

**Issue by yutianfanxing** [rbmonster/learning-note#22]
![image](https://user-images.githubusercontent.com/50042867/172807101-71e47b9f-2ed2-427d-9b4a-0b6770857068.png)

**Comment by rbmonster** [comment]
It seem gitee can't load github repository picture. Maybe an oss file storage url can fix this problem.
The gitee page service also have sensitive word scan, this repository some file can't pass the scan.

**Comment by makersy** [comment]
> It seem gitee can't load github repository picture. Maybe an oss file storage url can fix this problem. The gitee page service also have sensitive word scan, this repository some file can't pass the scan.

What about [gitbook](https://www.gitbook.com/) ?

**Comment by rbmonster** [comment]
Hi! I have fix the picture problem.
