### ISSUE TITLE
抽象工厂模式的图是不是错了？

### ISSUE THREAD

**Issue by Joey-Hu** [rbmonster/learning-note#7]
https://github.com/rbmonster/learning-note/blob/master/src/main/java/com/toc/CODEDESIGN_BOOK.md
AbstractFactory 和 FactoryProducer 位置标反了吧？

**Comment by rbmonster** [comment]
AbstractFactoryPatternDemo 类使用 FactoryProducer 来获取 AbstractFactory 对象，FactoryProducer 只是用来获取抽象工厂对象的。
