### ISSUE TITLE
修正拦截器描述错误

### ISSUE THREAD

**Issue by the404** [rbmonster/learning-note#8]
https://github.com/rbmonster/learning-note/blob/master/src/main/java/com/toc/FILTERANDINTERCEPTOR.md

**spring mvc的拦截器是只拦截controller而不拦截jsp,html 页面文件的。这就用到过滤器filter了，**

进过测试 拦截器可以在js,html 访问时被拦截到

![image](https://user-images.githubusercontent.com/5737075/121500026-81267200-ca10-11eb-9934-ae6aa618fac0.png)

**Comment by the404** [comment]
![image](https://user-images.githubusercontent.com/5737075/121500921-512b9e80-ca11-11eb-9b4b-d2f8f0771fcc.png)
直接访问静态html和js

**Comment by rbmonster** [comment]
you can change it to the correct description and create a pull request for this issue.
